#!/bin/bash

terraform apply

# Get the nameservers in the newly created hosted zone and format it to be friendly to the subsequent AWS CLI command.
name_servers_arg=`terraform show -json | jq -cr '.values.root_module.resources[] | select(.name | contains("site_zone")).values.name_servers[] | ("Name=" + .)'`

aws route53domains update-domain-nameservers \
    --region us-east-1 \
    --domain-name dailywombat.com \
    --nameservers $name_servers_arg
